@startuml devices
!include project.puml

remove pyvnm.*
restore pyvnm.vm.device.Device
restore pyvnm.vm.device.Screen
restore pyvnm.vm.device.CharScreen
restore pyvnm.vm.device.Keyboard
restore pyvnm.vm.device.DeviceBus
@enduml