@startuml event_loop_flow
!pragma useVerticalIf on

|Unidade de Controle|
start
while ((sig_term == false) e (i_begin <= pc <= i_end) ?) is (sim)
  :Acessa posição da memória indicada por
  PC e obtem uma instância de <i>Instruction</i>;
  
  :Obtêm ação do mapa de ações
  pelo valor do opcode;

  :Executa ação obtida passando
  o valor do operando;
  note right
    Ações de JUMP podem sinalizar o 
    bloqueio do PC para evitar que
    seu valor seja modificado
  end note
  if (PC está bloqueado ?) then (não )
    :Incrementa PC;
  else ( sim)
    :Desbloqueia PC;
    note right
      Se o PC estiver bloqueado, ele
      deve ser desbloqueado para
      que o programa continue seu
      fluxo sequencial
    end note
  endif
endwhile (não )
stop

@enduml