@startuml project
!include classes.iuml

pyvnm.vm.control.ControlUnit <.. pyvnm.vm.isa.InstructionSet
pyvnm.vm.device.Keyboard ..|> pyvnm.vm.device.Device
pyvnm.vm.device.Screen ..|> pyvnm.vm.device.Device
pyvnm.vm.device.CharScreen ..|> pyvnm.vm.device.Device
pyvnm.vm.isa.Instruction --|> pyvnm.vm.isa.Word
pyvnm.vm.control.ControlUnit --* pyvnm.vm.vnm.VonNeumannMachine : control_unit
pyvnm.vm.device.DeviceBus --o pyvnm.vm.state.MachineState : devices
pyvnm.vm.device.Device --o pyvnm.vm.device.DeviceBus : devices
pyvnm.vm.isa.Word --o pyvnm.vm.state.MachineState : acc
pyvnm.vm.isa.Word --o pyvnm.vm.state.MachineState : pc
pyvnm.vm.isa.Word --* pyvnm.vm.memory.Memory : data
pyvnm.vm.memory.Memory --o pyvnm.vm.state.MachineState : memory
pyvnm.vm.control.ControlUnit o- pyvnm.vm.state.MachineState : state
pyvnm.vm.state.MachineState --o pyvnm.system.loader.Dumper : state
pyvnm.vm.state.MachineState --o pyvnm.system.loader.Loader : state
pyvnm.vm.state.MachineState --* pyvnm.vm.vnm.VonNeumannMachine : state
pyvnm.vm.state.MachineState *- pyvnm.vm.utils.Lock : pc_lock
pyvnm.system.loader.Dumper <. pyvnm.vm.vnm.VonNeumannMachine
pyvnm.vm.vnm.VonNeumannMachine .> pyvnm.system.loader.Loader
@enduml