@startuml project
!include classes.iuml

pyvnm.vm.control.CPU <. pyvnm.vm.isa.InstructionSet
pyvnm.system.assembler.Assembler <. pyvnm.vm.isa.InstructionSet
pyvnm.vm.device.Keyboard .|> pyvnm.vm.device.Device
pyvnm.vm.device.Device <|.. pyvnm.vm.device.Screen
pyvnm.vm.device.Device <|.. pyvnm.vm.device.CharScreen
pyvnm.vm.device.Device <|.. pyvnm.vm.device.HardDrive
pyvnm.vm.control.CPU --* pyvnm.vm.vnm.VonNeumannMachine : cpu
pyvnm.vm.device.DeviceBus --o pyvnm.vm.state.CPUState : devices
pyvnm.vm.device.Device -o pyvnm.vm.device.DeviceBus : devices
pyvnm.vm.state.CPUState o- pyvnm.vm.isa.Word : acc
pyvnm.vm.state.CPUState o- pyvnm.vm.isa.Word : pc
pyvnm.vm.memory.Memory <. pyvnm.vm.isa.Word
pyvnm.vm.memory.Memory --o pyvnm.vm.state.CPUState : memory
pyvnm.vm.state.CPUState --o pyvnm.vm.control.CPU : state
pyvnm.vm.utils.Lock --* pyvnm.vm.state.CPUState : pc_lock


pyvnm.vm.vnm.VonNeumannMachine <- pyvnm.system.bootloader.Bootloader
pyvnm.vm.control.CPU --* pyvnm.system.bootloader.Bootloader : cpu


pyvnm.system.assembler.PseudoInstructionSet .> pyvnm.system.assembler.Assembler
pyvnm.system.assembler.Assembler <.. pyvnm.system.assembler.LineTokens
pyvnm.system.assembler.Assembler *-- pyvnm.system.assembler.AssemblerState : state
pyvnm.system.assembler.Assembler --> pyvnm.vm.vnm.VonNeumannMachine
' pyvnm.vm.vnm.VonNeumannMachine <.up. pyvnm.system.assembler.Assembler
pyvnm.system.relocator.Relocator -> pyvnm.vm.vnm.VonNeumannMachine
pyvnm.vm.vnm.VonNeumannMachine <-- pyvnm.system.linker.Linker
pyvnm.vm.vnm.VonNeumannMachine --[hidden]> pyvnm.system.fs.FileSytem

pyvnm.vm.vnm.VonNeumannMachine --* pyvnm.system.cli.Terminal : vnm
pyvnm.system.user.User -* pyvnm.system.cli.Terminal : user
pyvnm.system.fs.FileSytem -* pyvnm.system.user.User : filesystem
@enduml