@startuml terminal_DMP
start
  :Lê parâmetro P1
  Lê parâmetro P2
  Lê parâmetro P3;
  note right
    P1: nome do arquivo de saída do dumper
    P2: posição inicial do descarregamento
    P3: posição final do descarregamento
  end note
  :dump <- Terminal.vnm.dump(P2, P3);
  note right
    Gera o dump da memória a partir da chamada do
    método **dump()** da classe VonNeumannMachine
  end note
  :filesystem <- Terminal.user.get_fs()
  filesystem.write(P1, dump);
  note right
    Acessa o sistema de arquivos subjacente ao usuário
    logado e escreve o dump gerado no arquivo 
    especificado pelo parâmetro P1
  end note
stop
@enduml