@startuml terminal_SDR
start
  :filesystem <- Terminal.user.get_fs();
  note right
  Acessa o sistema de arquivos subjacente ao 
  usuário autenticado
  end note
  :filesystem.list_sys();
  note right
    Lista os programas de sistema existentes
  end note
stop
@enduml