# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath('../..'))


# -- Project information -----------------------------------------------------

project = 'Simulador da Máquina de Von Neumann'
copyright = '2023, N. M. Cardoso, R. N. Fleury'
author = 'N. M. Cardoso, R. N. Fleury'

# The full version, including alpha/beta/rc tags
release = '0.1'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
  'sphinx.ext.autodoc',
  'sphinx.ext.autosummary',
  'sphinx.ext.mathjax',
  'sphinx.ext.viewcode',
  'sphinx.ext.githubpages',
  'sphinx.ext.doctest',
  'sphinx.ext.intersphinx',
  # 'sphinx_copybutton',
  # 'sphinxcontrib.napoleon',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'pt_BR'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


source_suffix = '.rst'




# -- Extension configuration -------------------------------------------------
autodoc_class_signature = 'separated'
# autodoc_member_order = 'groupwise'
autodoc_default_options = {
  'member-order': 'groupwise',
  'exclude-members': '__init__',
  'undoc-members': True,
}


intersphinx_mapping = {
  'python': ('https://docs.python.org/3/', None),
#   'numpy': ('https://numpy.org/devdocs/', None),
#   'scipy': ('https://docs.scipy.org/doc/scipy', None),
#   'sklearn': ('https://scikit-learn.org/stable/', None),
#   'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
#   'matplotlib': ('https://matplotlib.org/stable/', None),
}


napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = True
napoleon_include_special_with_doc = False
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = True
napoleon_use_ivar = True
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_use_keyword = True
napoleon_custom_sections = None



autosummary_generate = True


pygments_style = 'sphinx'
