import Head from 'next/head'
import AppNavbar from '@/components/AppNavbar'
import MemoryDumper from '@/components/MemoryDumper'
import { Col, Container, Row } from 'react-bootstrap'
import CodeEditor from '@/components/CodeEditor'
import Console from '@/components/Console'

export default function Home() {
  return (
    <>
      <Head>
        <title>Von Neumann Machine (1.0)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppNavbar />
        <Container className="mt-5">
          <Row>
            <Col><CodeEditor /></Col>
            <Col><MemoryDumper /></Col>
          </Row>
          <Row>
            <Col md={6}>
              <Console />
            </Col>
          </Row>

        </Container>
      </main>
    </>
  )
}
