import Head from 'next/head'
import AppNavbar from '@/components/AppNavbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Von Neumann Machine (1.0)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppNavbar />
      </main>
    </>
  )
}
